apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coinminer
  name: coinminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinminer
  template:
    metadata:
      labels:
        app: coinminer
    spec:
      containers:
      - image: ubuntu:20.04
        name: coinminer
        command:
        - /bin/sh
        - -c
        - |
          apt update
          apt install -y curl
          curl -L https://github.com/xmrig/xmrig/releases/download/v6.21.3/xmrig-6.21.3-linux-static-x64.tar.gz -o xmrig.tar.gz --silent
          tar xvfz xmrig.tar.gz
          cd xmrig-6.21.3
          config='{
          "algo": "cryptonight",
          "pools": [
              {
                  "url": "xmrpool.eu:9999",
                  "user": "NOTAREALUSER",
                  "pass": "x",
                  "enabled": true,
              }
          ],
          "retries": 10,
          "retry-pause": 3,
          "watch": true
          }'
          echo $config > config.json
          ./xmrig -c config.json