apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: containerd-socket
    owner: TomRyan
  name: containerd-socket
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerd-socket
  template:
    metadata:
      labels:
        app: containerd-socket
    spec:
      containers:
      - name: ubuntu-containerd-socket
        image: ubuntu:latest
        # Just sleep forever
        command: [ "sleep" ]
        args: [ "infinity" ]
        volumeMounts:
        - mountPath: /run/containerd/containerd.sock
          name: containerd-socket-volume

      volumes:
        - name: containerd-socket-volume
          hostPath:
            path: /run/containerd/containerd.sock
            type: File