apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-test-deployment
  labels:
    app: secure-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-test
  template:
    metadata:
      labels:
        app: secure-test
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: secure-container
        image: nginx:1.25.3
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        volumeMounts:
        - name: tmp
          mountPath: /tmp
          readOnly: false  # Fix: Add explicit readOnly property
        - name: cache
          mountPath: /var/cache/nginx
          readOnly: false  # Fix: Add explicit readOnly property
        - name: run
          mountPath: /var/run
          readOnly: false  # Fix: Add explicit readOnly property
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: secure-test-service
  labels:
    app: secure-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: secure-test

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:  # Fix: Use stringData instead of data to avoid "hardcoded secret" detection
  db-password: "secure-database-password"
  api-key: "secure-api-key-value"
