apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-test-deployment
  labels:
    app: secure-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-test
  template:
    metadata:
      labels:
        app: secure-test
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001  # Higher UID to avoid "low UID" issue
        runAsGroup: 10001
        fsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: secure-container
        image: nginx:1.25.3
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001  # Higher UID to avoid "low UID" issue
          runAsGroup: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        # Fix: Add memory limits (this was flagged as undefined)
        resources:
          limits:
            cpu: 100m
            memory: 128Mi  # This was missing and flagged
          requests:
            cpu: 50m
            memory: 64Mi
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: api-key
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: cache
          mountPath: /var/cache/nginx
        - name: run
          mountPath: /var/run
      volumes:
      - name: tmp
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: run
        emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: secure-test-service
  labels:
    app: secure-test
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: secure-test

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  db-password: c2VjdXJlLWRhdGFiYXNlLXBhc3N3b3Jk
  api-key: c2VjdXJlLWFwaS1rZXktdmFsdWU=
