name: actions-jobs
on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write
  actions: read

env:
  FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }} 
  FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
  ECR_REPO: kkuhns
  ECR_TAG: demo

jobs:
  sec-scans:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      run: |
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "This is a PR - scanning only changed files"
          
          # Get ALL files changed in this PR (no filtering)
          git diff --name-only origin/${{ github.base_ref }}..HEAD > all_changed_files.txt
          
          # Exclude only .github workflow files (we don't want to scan those)
          grep -v '^\.github/' all_changed_files.txt > changed_files.txt || true
          
          if [ -s changed_files.txt ]; then
            echo "Changed files found (FCS will determine which are IaC):"
            cat changed_files.txt
            echo "has_changes=true" >> $GITHUB_OUTPUT
            echo "scan_mode=pr_changes" >> $GITHUB_OUTPUT
          else
            echo "No files changed in this PR (excluding workflow files)"
            echo "has_changes=false" >> $GITHUB_OUTPUT
            echo "scan_mode=pr_changes" >> $GITHUB_OUTPUT
          fi
        else
          echo "Manual trigger - scanning entire repository"
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "scan_mode=full_repo" >> $GITHUB_OUTPUT
        fi

    - name: Create output directory
      run: mkdir -p ./scan-results

    - name: Run FCS IaC Scan
      uses: crowdstrike/fcs-action@v1.1.0
      id: fcs
      if: steps.changed-files.outputs.has_changes == 'true'
      with:
        falcon_client_id: ${{ secrets.FALCON_CLIENT_ID }}
        falcon_region: 'us-1'
        path: '.'
        report_formats: 'sarif'
        output_path: './scan-results'
        fail_on: 'critical=1,high=1'
      env:
        FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}

    - name: Check FCS scan results
      if: always() && steps.changed-files.outputs.has_changes == 'true' && github.event_name == 'pull_request'
      run: |
        echo "FCS scan exit code: ${{ steps.fcs.outputs.exit-code }}"
        
        if [ -f "./scan-results/"*"-scan-results.sarif" ]; then
          CRITICAL_HIGH_COUNT=$(jq '[.runs[].results[] | select(.level == "error")] | length' ./scan-results/*-scan-results.sarif 2>/dev/null || echo "0")
          
          echo "Critical/High severity findings: $CRITICAL_HIGH_COUNT"
          
          if [ "$CRITICAL_HIGH_COUNT" -gt "0" ]; then
            echo "::error::Found $CRITICAL_HIGH_COUNT critical/high severity security issues"
            exit 1
          else
            echo "::notice::No critical/high severity issues found. Medium/low issues are acceptable."
            echo "PR can proceed - only medium/low severity findings present."
          fi
        else
          echo "::warning::No scan results file found, but exit code was ${{ steps.fcs.outputs.exit-code }}"
        fi

    - name: No changes detected
      if: steps.changed-files.outputs.has_changes == 'false'
      run: |
        echo "::notice::No files were changed in this PR (excluding workflow files). Skipping security scan."
        echo "Scan mode: ${{ steps.changed-files.outputs.scan_mode }}"

    - name: Transform SARIF file
      if: always() && steps.changed-files.outputs.has_changes == 'true'
      run: |
        if ls ./scan-results/*-scan-results.sarif 1> /dev/null 2>&1; then
          cp ./scan-results/*-scan-results.sarif original.sarif
          jq '
            .runs[].tool.driver.informationUri = "https://www.crowdstrike.com" |
            .runs[].tool.driver.rules[] |= (
              if .defaultConfiguration.level == "critical" or .defaultConfiguration.level == "high" then .defaultConfiguration.level = "error"
              elif .defaultConfiguration.level == "medium" then .defaultConfiguration.level = "warning"
              elif .defaultConfiguration.level == "low" or .defaultConfiguration.level == "informational" then .defaultConfiguration.level = "note"
              else .defaultConfiguration.level = "warning"
              end
            )
          ' original.sarif > scan-results.sarif
        else
          echo "No SARIF file found to transform"
        fi

    - name: Upload SARIF report to GitHub Code scanning
      uses: github/codeql-action/upload-sarif@v3
      if: always() && hashFiles('scan-results.sarif') != ''
      with:
        sarif_file: scan-results.sarif

    - name: Scan Summary
      if: always()
      run: |
        echo "## IaC Security Scan Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Trigger**: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Scan Mode**: ${{ steps.changed-files.outputs.scan_mode }}" >> $GITHUB_STEP_SUMMARY
        echo "- **FCS Exit Code**: ${{ steps.fcs.outputs.exit-code }}" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ github.event_name }}" == "pull_request" ] && [ -f changed_files.txt ]; then
          echo "- **Changed Files (FCS will filter for IaC)**:" >> $GITHUB_STEP_SUMMARY
          while read -r file; do
            echo "  - $file" >> $GITHUB_STEP_SUMMARY
          done < changed_files.txt
        fi

#**************************************************************************************************************
# COMMENTED OUT - Container scanning sections until we can get FCS CLI image assessment working
#**************************************************************************************************************

    # - name: Ensure docker is not running
    #   run: |
    #     sudo systemctl stop docker.service
    #     sudo systemctl stop docker.socket

    # - name: Podman build
    #   run: |
    #     podman build --platform linux/amd64 -t ${{ secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-2.amazonaws.com/${{ env.ECR_REPO }}:${{ env.ECR_TAG }} .
    #     systemctl --user enable --now podman.socket

    # - name: Configure AWS credentials for FCS CLI
    #   uses: aws-actions/configure-aws-credentials@v4
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_FCS }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_FCS }}
    #     aws-region: us-west-2

    # - name: Download and Update FCS CLI
    #   run: |
    #     echo "Downloading FCS CLI from S3..."
    #     aws s3 cp s3://fcs-cli-beta-testing-kc/fcs /usr/local/bin/fcs
    #     chmod +x /usr/local/bin/fcs
    #     
    #     echo "Current FCS CLI version:"
    #     fcs version || echo "Could not get version"
    #     
    #     echo "Updating FCS CLI to latest version..."
    #     fcs update || echo "Update failed or not needed"
    #     
    #     echo "Updated FCS CLI version:"
    #     fcs version || echo "Could not get version after update"

    # - name: Configure FCS CLI
    #   env:
    #     FCS_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
    #     FCS_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
    #     FCS_FALCON_REGION: "us-1"
    #   run: |
    #     fcs configure --client-id "$FCS_CLIENT_ID" --client-secret "$FCS_CLIENT_SECRET" --falcon-region "$FCS_FALCON_REGION"
   
    # - name: Run FCS CLI Image Scan
    #   run: |
    #     echo "Scanning container image..."
    #     fcs scan image ${{ secrets.AWS_ACCOUNT_ID}}.dkr.ecr.us-east-2.amazonaws.com/${{ env.ECR_REPO }}:${{ env.ECR_TAG }} --platform linux/amd64 --upload
